### ISSUE TITLE
大神 为什么我只能打印一部分？

### ISSUE THREAD

**Issue by tengFuShangGitHub** [Halley-Wong/HLBluetoothDemo#1]
是不是在写入的时候被限制了 ？

**Comment by tengFuShangGitHub** [comment]
大神能发个qq吗 ？有几个问题请教你

**Comment by Halley-Wong** [comment]
你那是什么情况？只打印前几行？

**Comment by tengFuShangGitHub** [comment]
嗯嗯 ，想给你发个图片不知道怎么发  ，能留个邮箱吗 ？

**Comment by Halley-Wong** [comment]
![0c3387da-7340-4b24-8c3c-8253044a080f](https://cloud.githubusercontent.com/assets/7069859/15167588/b1fd43ca-175c-11e6-9e38-eac47a883737.png)
翻译下两行英文，把图片拖进输入框就可以了。

**Comment by tengFuShangGitHub** [comment]
![Uploading 0365E569-FF8E-4C90-8EF6-3EE4EFB53AE3.png…]()

![](https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif)

**Comment by Halley-Wong** [comment]
。。。。拖进去你要等它上传成功了再点Comment。

**Comment by tengFuShangGitHub** [comment]
[Uploading 0365E569-FF8E-4C90-8EF6-3EE4EFB53AE3.png.zip…]()

**Comment by tengFuShangGitHub** [comment]
[0365E569-FF8E-4C90-8EF6-3EE4EFB53AE3.png.zip](https://github.com/Halley-Wong/HLBluetoothDemo/files/258473/0365E569-FF8E-4C90-8EF6-3EE4EFB53AE3.png.zip)

**Comment by tengFuShangGitHub** [comment]
你看看能看见吗 ？

**Comment by Halley-Wong** [comment]
看不见，你先对比下我刚才修改readme 里附加部分，定位下问题。

**Comment by tengFuShangGitHub** [comment]
大神你有讨论群吗 ？

**Comment by Halley-Wong** [comment]
495265141，你加我吧
